meta_product_name: "Talk About"
meta_title: "Talk About - Participa de los mejores eventos online"
meta_description: "¿Estás buscando eventos online? Viajes, deportes, música, cursos y mucho más. Todo en el mismo sitio. Regístrate y comienza a participar."
meta_image: "cover.png" 
# twitter_account: "@product_twitter_account"  